### ISSUE TITLE
Update native library to 1.2.3

### ISSUE THREAD

**Issue by jochembroekhoff** [NAXAM/bottomnavigationviewex-android-binding#3]
A new version of BottomNavigationViewEx has been released:
https://github.com/ittianyu/BottomNavigationViewEx/releases/tag/1.2.3

**Comment by tuyen-vuduc** [comment]
Pull request is very welcome, @jochembroekhoff.

**Comment by tuyen-vuduc** [comment]
Updated to v1.2.4
